In [24]:
import numpy as np
additionalCosts = np.array(["Biopsy", "AE", "Admin", "Concat"])
biopsyCost  = 22
aeCost = 15
adminCost = 33
concatCost = 40

In [28]:
## Parameters of dosing in Induction phase
indFreq = 2
indCycleLength = 8
indDuration = 12 ##which is number of cycles in that phase
indDose = 77

## Parameters of dosing in Maintenance phase
mainFreq = 3
mainCycleLength = 12
mainDuration = 15 ##which is number of cycles in that phase
mainDose = 111 

In [29]:
#Biopsy costs are per cycle
drugCost = np.zeros((indCycleLength*indDuration))
biopsyCostCalendar = np.copy(drugCost)
biopsyCostCalendar[0: :indCycleLength] = biopsyCost
biopsyCostCalendar

array([ 22.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  22.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,  22.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,  22.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  22.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,  22.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,  22.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,  22.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  22.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,  22.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,  22.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
        22.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [30]:
#aeCost are per week
aeCostCalendar = np.copy(drugCost)
aeCostCalendar[0: :7] = aeCost
aeCostCalendar

array([ 15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,   0.,   0.,   0.,
         0.,   0.,   0.,  15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,
         0.,   0.,   0.,   0.,   0.,   0.,  15.,   0.,   0.,   0.,   0.,
         0.,   0.,  15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,   0.,
         0.,   0.,   0.,   0.,   0.,  15.,   0.,   0.,   0.,   0.,   0.,
         0.,  15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,   0.,   0.,
         0.,   0.,   0.,   0.,  15.,   0.,   0.,   0.,   0.,   0.,   0.,
        15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,   0.,   0.,   0.,
         0.,   0.,   0.,  15.,   0.,   0.,   0.,   0.])

In [50]:
#Admin cost are per month
daysInMonth = np.array([0,31,59,90,120,151,181,212,243,273,304,334,365,396,424,455,485,516,546,577,608,638,669,699,730,761,789,820,850,881,911,942,973,1003,1034,1064,1095,1126,1154,1185,1215,1246,1276,1307,1338,1368,1399,1429,1460,1491,1519,1550,1580,1611,1641,1672,1703,1733,1764,1794])
adminCostCalendar = np.copy(drugCost)
np.put(adminCostCalendar, daysInMonth[daysInMonth<indCycleLength*indDuration], adminCost)
adminCostCalendar

array([ 33.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  33.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,  33.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,  33.,   0.,   0.,   0.,   0.,   0.])

In [53]:
np.zeros((2,3,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])